knowledge/urls.py
from django.conf.urls import patterns, url
from knowledge.views import *

urlpatterns = patterns('knowledge.views',
    url(r'^$', 'knowledge_index', name='knowledge_index'),

    url(r'^questions/$', 'knowledge_list', name='knowledge_list'),

    url(r'^questions/(?P<question_id>\d+)/$',
        'knowledge_thread', name='knowledge_thread_no_slug'),

    url(r'^questions/(?P<category_slug>[a-z0-9-_]+)/$', 'knowledge_list',
        name='knowledge_list_category'),

    url(r'^questions/(?P<question_id>\d+)/(?P<slug>[a-z0-9-_]+)/$',
        'knowledge_thread', name='knowledge_thread'),

    url(r'^questions/edit/(?P<question_id>\d+)/$',
        'knowledge_edit', name='knowledge_edit'),

    url(r'^moderate/(?P<model>[a-z]+)/'
        r'(?P<lookup_id>\d+)/(?P<mod>[a-zA-Z0-9_]+)/$',
        'knowledge_moderate', name='knowledge_moderate'),

    url(r'^ask/$', 'knowledge_ask', name='knowledge_ask'),

    url(r'categories/$', CategoryList.as_view(), name="category_list"),
    url(r'categories/add/$', CategoryCreate.as_view(), name='category_add'),
    url(r'categories/(?P<pk>\d+)/$', CategoryUpdate.as_view(), name='category_update'),
    url(r'categories/(?P<pk>\d+)/delete/$', CategoryDelete.as_view(), name='category_delete'),

)

knowledge/models.py
from knowledge import settings

import django
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings as django_settings

from knowledge.managers import QuestionManager, ResponseManager
from knowledge.signals import knowledge_post_save

STATUSES = (
    ('public', _('Public')),
    ('private', _('Private')),
    ('internal', _('Internal')),
)


STATUSES_EXTENDED = STATUSES + (
    ('inherit', _('Inherit')),
)


class Category(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    lastchanged = models.DateTimeField(auto_now=True)

    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class KnowledgeBase(models.Model):
    """
    The base class for Knowledge models.
    """
    is_question, is_response = False, False

    added = models.DateTimeField(auto_now_add=True)
    lastchanged = models.DateTimeField(auto_now=True)

    user = models.ForeignKey('auth.User' if django.VERSION < (1, 5, 0) else django_settings.AUTH_USER_MODEL, blank=True,
                             null=True, db_index=True)
    alert = models.BooleanField(default=settings.ALERTS,
        verbose_name=_('Alert'),
        help_text=_('Check this if you want to be alerted when a new'
                        ' response is added.'))

    # for anonymous posting, if permitted
    name = models.CharField(max_length=64, blank=True, null=True,
        verbose_name=_('Name'),
        help_text=_('Enter your first and last name.'))
    email = models.EmailField(blank=True, null=True,
        verbose_name=_('Email'),
        help_text=_('Enter a valid email address.'))

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.user and self.name and self.email \
                and not self.id:
            # first time because no id
            self.public(save=False)

        if settings.AUTO_PUBLICIZE and not self.id:
            self.public(save=False)

        super(KnowledgeBase, self).save(*args, **kwargs)

    #########################
    #### GENERIC GETTERS ####
    #########################

    def get_name(self):
        """
        Get local name, then self.user's first/last, and finally
        their username if all else fails.
        """
        name = (self.name or (self.user and (
            u'{0} {1}'.format(self.user.first_name, self.user.last_name).strip()\
            or self.user.username
        )))
        return name.strip() or _("Anonymous")

    get_email = lambda s: s.email or (s.user and s.user.email)
    get_pair = lambda s: (s.get_name(), s.get_email())
    get_user_or_pair = lambda s: s.user or s.get_pair()

    ########################
    #### STATUS METHODS ####
    ########################

    def can_view(self, user):
        """
        Returns a boolean dictating if a User like instance can
        view the current Model instance.
        """

        if self.status == 'inherit' and self.is_response:
            return self.question.can_view(user)

        if self.status == 'internal' and user.is_staff:
            return True

        if self.status == 'private':
            if self.user == user or user.is_staff:
                return True
            if self.is_response and self.question.user == user:
                return True

        if self.status == 'public':
            return True

        return False

    def switch(self, status, save=True):
        self.status = status
        if save:
            self.save()
    switch.alters_data = True

    def public(self, save=True):
        self.switch('public', save)
    public.alters_data = True

    def private(self, save=True):
        self.switch('private', save)
    private.alters_data = True

    def inherit(self, save=True):
        self.switch('inherit', save)
    inherit.alters_data = True

    def internal(self, save=True):
        self.switch('internal', save)
    internal.alters_data = True


class Question(KnowledgeBase):
    is_question = True
    _requesting_user = None

    title = models.CharField(max_length=255,
        verbose_name=_('Question'),
        help_text=_('Enter your question or suggestion.'))
    body = models.TextField(blank=True, null=True,
        verbose_name=_('Description'),
        help_text=_('Please offer details. Markdown enabled.'))

    status = models.CharField(
        verbose_name=_('Status'),
        max_length=32, choices=STATUSES,
        default='private', db_index=True)

    locked = models.BooleanField(default=False)

    categories = models.ManyToManyField('knowledge.Category', blank=True)

    objects = QuestionManager()

    class Meta:
        ordering = ['-added']
        verbose_name = _('Question')
        verbose_name_plural = _('Questions')

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        from django.template.defaultfilters import slugify

        if settings.SLUG_URLS:
            return ('knowledge_thread', [self.id, slugify(self.title)])
        else:
            return ('knowledge_thread_no_slug', [self.id])

    def inherit(self):
        pass

    def internal(self):
        pass

    def lock(self, save=True):
        self.locked = not self.locked
        if save:
            self.save()
    lock.alters_data = True

    ###################
    #### RESPONSES ####
    ###################

    def get_responses(self, user=None):
        user = user or self._requesting_user
        qs = self.responses.order_by('-accepted', 'added').select_related('user')
        if user:
            return [r for r in qs if r.can_view(user)]
        else:
            return qs

    def answered(self):
        """
        Returns a boolean indictating whether there any questions.
        """
        return bool(self.get_responses())

    def accepted(self):
        """
        Returns a boolean indictating whether there is a accepted answer
        or not.
        """
        return any([r.accepted for r in self.get_responses()])

    def clear_accepted(self):
        self.get_responses().update(accepted=False)
    clear_accepted.alters_data = True

    def accept(self, response=None):
        """
        Given a response, make that the one and only accepted answer.
        Similar to StackOverflow.
        """
        self.clear_accepted()

        if response and response.question == self:
            response.accepted = True
            response.save()
            return True
        else:
            return False
    accept.alters_data = True

    def states(self):
        """
        Handy for checking for mod bar button state.
        """
        return [self.status, 'lock' if self.locked else None]

    @property
    def url(self):
        return self.get_absolute_url()


class Response(KnowledgeBase):
    is_response = True

    question = models.ForeignKey('knowledge.Question',
        related_name='responses')

    body = models.TextField(blank=True, null=True,
        verbose_name=_('Response'),
        help_text=_('Please enter your response. Markdown enabled.'))
    status = models.CharField(
        verbose_name=_('Status'),
        max_length=32, choices=STATUSES_EXTENDED,
        default='inherit', db_index=True)
    accepted = models.BooleanField(default=False)

    objects = ResponseManager()

    class Meta:
        ordering = ['added']
        verbose_name = _('Response')
        verbose_name_plural = _('Responses')

    def __unicode__(self):
        return self.body[0:100] + u'...'

    def states(self):
        """
        Handy for checking for mod bar button state.
        """
        return [self.status, 'accept' if self.accepted else None]

    def accept(self):
        self.question.accept(self)
    accept.alters_data = True


# cannot attach on abstract = True... derp
models.signals.post_save.connect(knowledge_post_save, sender=Question)
models.signals.post_save.connect(knowledge_post_save, sender=Response)

knowledge/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from knowledge import settings
from knowledge.models import Question, Response, Category

OPTIONAL_FIELDS = ['alert', 'phone_number', 'categories']


__todo__ = """
This is serious badness. Really? Functions masquerading as
clases? Lame. This should be fixed. Sorry.
                                                    ~bryan
"""


def QuestionForm(user, *args, **kwargs):
    """
    Build and return the appropriate form depending
    on the status of the passed in user.
    """

    if user.is_anonymous():
        if not settings.ALLOW_ANONYMOUS:
            return None
        else:
            selected_fields = ['name', 'email', "title", "body", "categories"]
    else:
        selected_fields = ['user', "title", "body", "categories", 'status']

    if settings.ALERTS:
        selected_fields += ['alert']

    class _QuestionForm(forms.ModelForm):
        def __init__(self, *args, **kwargs):
            super(_QuestionForm, self).__init__(*args, **kwargs)

            for key in self.fields:
                if not key in OPTIONAL_FIELDS:
                    self.fields[key].required = True

            # hide the internal status for non-staff
            qf = self.fields.get('status', None)
            if qf and not user.is_staff:
                choices = list(qf.choices)
                choices.remove(('internal', _('Internal')))
                qf.choices = choices

            # a bit of a hack...
            # hide a field, and use clean to force
            # a specific value of ours
            filtered_fields = ['user']
            if not user.is_staff:
                filtered_fields.append('categories')
            for key in filtered_fields:
                qf = self.fields.get(key, None)
                if qf:
                    qf.widget = qf.hidden_widget()
                    qf.required = False

        title = forms.CharField(widget=forms.TextInput(
                                        attrs={'class': 'span12'}
                                        )
                                )
        body = forms.CharField(widget=forms.Textarea(
                                        attrs={
                                               'rows': 10,
                                               'class': 'span12'}
                                               )
                                )
        categories = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(
                                                        attrs={'class': 'span12'}
                                                    ),
                                                    queryset=Category.objects.all(),
                                                    help_text=None,
                                                    required=False
                                                    )

        class Meta:
            model = Question
            fields = selected_fields

    return _QuestionForm(*args, **kwargs)


def ResponseForm(user, question, *args, **kwargs):
    """
    Build and return the appropriate form depending
    on the status of the passed in user and question.
    """

    if question.locked:
        return None

    if not settings.FREE_RESPONSE and not \
            (user.is_staff or question.user == user):
        return None

    if user.is_anonymous():
        if not settings.ALLOW_ANONYMOUS:
            return None
        else:
            selected_fields = ['name', 'email']
    else:
        selected_fields = ['user']

    selected_fields += ['body', 'question']

    if user.is_staff:
        selected_fields += ['status']

    if settings.ALERTS:
        selected_fields += ['alert']

    class _ResponseForm(forms.ModelForm):
        def __init__(self, *args, **kwargs):
            super(_ResponseForm, self).__init__(*args, **kwargs)

            for key in self.fields:
                if not key in OPTIONAL_FIELDS:
                    self.fields[key].required = True

            # a bit of a hack...
            for key in ['user', 'question']:
                qf = self.fields.get(key, None)
                if qf:
                    qf.widget = qf.hidden_widget()
                    qf.required = False


        body = forms.CharField(widget=forms.Textarea(
                                        attrs={
                                               'rows': 10,
                                               'class': 'span12'}
                                               ),
                               label="Response"
                                )

        def clean_user(self):
            return user

        def clean_question(self):
            return question

        class Meta:
            model = Response
            fields = selected_fields

    return _ResponseForm(*args, **kwargs)

knowledge/templates/django_knowledge/ask.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Ask a Question" %}{{ block.super }}{% endblock title %}

{% block knowledge_widgets %}
<div class="dk-widget">
  <h3>{% trans "Ask a Question" %}</h3>
  <hr />

  {% if form %}
    {% include "django_knowledge/form.html" with submit_value="Submit this support request" submit_and="and we'll get back to you as soon as possible." %}
  {% else %}
    <p class="center"><em>{% trans "Please log in to ask a question." %}</em></p>
  {% endif %}

</div>
{% endblock knowledge_widgets %}

knowledge/templates/django_knowledge/base.html
<!doctype html>
<html lang="en">
<head>

  <meta charset="utf-8">
  
  <title>{% block title %}{% endblock title %} | Support Center</title>
  
  <link rel="stylesheet" href="{{ STATIC_URL }}knowledge/css/reset.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}knowledge/css/main.css">

</head>

<body>

<div class="wrapper">
  
  {% block knowledge_inner %}
  {% endblock knowledge_inner %}

</div>
  
</body>
</html>

knowledge/templates/django_knowledge/category_confirm_delete.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Support" %}{{ block.super }}{% endblock title %}

{% block knowledge_widgets %}

<span style="font-size: 18px;">You want delete <a href="{% url "knowledge_list_category" category.slug %}" style="color: lightskyblue">{{ category.title }}</a> category. Go next?</span>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-info" value="Delete it!">
</form>
{% endblock knowledge_widgets %}

knowledge/templates/django_knowledge/category_form.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Support" %}{{ block.super }}{% endblock title %}


{% block knowledge_widgets %}
<form id="form" action="{{ submit_url }}" method="post" class="form-horizontal">
  {% csrf_token %}

  {% for field in form.visible_fields %}
    <div class="control-group field-{{ field.html_name }}">
        <label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}: {% if field.field.required %}<small><em class="quiet">({% trans "required" %})</em></small>{% endif %}
          {% if field.field.help_text %}
          {% endif %}
        </label>
      <div class="controls">
          {{ field }}
          {% if field.field.help_text %}
          <span class="help-block">{{ field.field.help_text }}</span>
          {% endif %}
      </div>
      {{ field.errors }}
    </div>
  {% endfor %}

  {% for field in form.hidden_fields %}{{ field }}{% endfor %}

  <button id="submit_button" class="btn btn-large btn-block btn-primary" type="submit" value="{% trans Submit %}">Submit</button>

</form>
<script src="/static/admin/js/urlify.js"></script>
<script type="text/javascript">
(function($) {
    $.fn.prepopulate = function(dependencies, maxLength) {
        /*
            Depends on urlify.js
            Populates a selected field with the values of the dependent fields,
            URLifies and shortens the string.
            dependencies - array of dependent fields id's
            maxLength - maximum length of the URLify'd string
        */
        return this.each(function() {
            var field = $(this);

            field.data('_changed', false);
            field.change(function() {
                field.data('_changed', true);
            });

            var populate = function () {
                // Bail if the fields value has changed
                if (field.data('_changed') == true) return;

                var values = [];
                $.each(dependencies, function(i, field) {
                  if ($(field).val().length > 0) {
                      values.push($(field).val());
                  }
                })
                field.val(URLify(values.join(' '), maxLength));
            };

            $(dependencies.join(',')).keyup(populate).change(populate).focus(populate);
        });
    };
})(jQuery);
</script>

<script type="text/javascript">
  $(document).ready(function(){
    $('#form').on('submit', function(e){
      $('#submit_button').attr('disabled', true);
    });
    $("#id_slug").prepopulate(["#id_title"], 50);
  });
</script>
{% endblock knowledge_widgets %}

knowledge/templates/django_knowledge/category_list.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Support" %}{{ block.super }}{% endblock title %}

{% block knowledge_widgets %}
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Category</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>

    {% for category in object_list %}
    <tr>
        <td><a href="{% url "knowledge_list_category" category.slug %}">{{ category.title }}</a></td>
        <td><a class="btn btn-success" href="{% url "category_update" category.id %}">Edit</a><a class="btn btn-danger" href="{% url "category_delete" category.id %}">Delete</a></td>
    </tr>
    {% endfor %}

    </tbody>
</table>
Or add new <a class="btn btn-info" href="{% url "category_add" %}">here</a>

{% endblock knowledge_widgets %}

knowledge/templates/django_knowledge/form.html
{% load i18n %}
{% load url from future %}

<form id="form" action="{{ submit_url }}" method="post" class="form-horizontal">
  {% csrf_token %}

  {% for field in form.visible_fields %}
    <div class="control-group field-{{ field.html_name }}">
        <label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}: {% if field.field.required %}<small><em class="quiet">({% trans "required" %})</em></small>{% endif %}
          {% if field.field.help_text %}
          {% endif %}
        </label>
      <div class="controls">
          {{ field }}
          {% if field.field.help_text %}
          <span class="help-block">{{ field.field.help_text }}</span>
          {% endif %}
      </div>
      {{ field.errors }}
    </div>
  {% endfor %}

  {% for field in form.hidden_fields %}{{ field }}{% endfor %}
  {% for field in form.hidden_fields %}{{ field }}{% endfor %}

  <button id="submit_button" class="btn btn-large btn-block btn-primary" type="submit" value="{% trans submit_value %}">{% trans submit_value %}</button>

</form>
<script type="text/javascript">
  $(document).ready(function(){
    $("#id_categories").select2();
    $('#form').on('submit', function(e){
      $('#submit_button').attr('disabled', true);
    });
  });
</script>

knowledge/templates/django_knowledge/index.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Support" %}{{ block.super }}{% endblock title %}

{% block knowledge_widgets %}

<div class="dk-widget">
  <h3>{% blocktrans with count=questions|length %}Top {{ count }} Questions{% endblocktrans %}</h3>
  <hr />

  {% include 'django_knowledge/question_list.html' %}
</div>

{% endblock knowledge_widgets %}

knowledge/templates/django_knowledge/inner.html
{% extends BASE_TEMPLATE|default:'django_knowledge/base.html' %}

{% load i18n %}
{% load url from future %}

{% block knowledge_inner %}

<div class="dk-inner">
  
  {% include "django_knowledge/welcome.html" %}

  <div class="dk-search">
    <form action="{% if category %}{% url "knowledge_list_category" category.slug %}{% else %}{% url "knowledge_list" %}{% endif %}" method="get">
      <input class="question-search" {% if search %}value="{{ search|force_escape }}"{% else %}placeholder="{% trans "Start typing your question here." %}"{% endif %} type="text" name="title"/> <input value="Search" type="submit" class="submit-question-search" />
    </form>
    <div class="clear"></div>
  </div>

  <div class="dk-content">
    {% block knowledge_widgets %}
      
    {% endblock knowledge_widgets %}
  </div>

  {% block sidebar %}
  <div class="dk-sidebar">
    <div class="inner">
      {% include "django_knowledge/sidebar.html" %}
    </div>
  </div>
  {% endblock %}
  <div class="clear"></div>
</div>

{% endblock knowledge_inner %}

knowledge/templates/django_knowledge/list.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}
{% load url from future %}

{% load knowledge_tags %}

{% block title %}Showing {{ questions.paginator.count }} results{% if search %} for {{ search }}{% endif %}{% if category %} in {{ category.title }} category{% endif %}{{ block.super }}{% endblock title %}

{% block knowledge_widgets %}

<div class="dk-widget">
  {# dunno how to do translation on this nasty block... #}
  <h3>Showing {{ counter }} results{% if search %} for <em>{{ search }}</em>{% endif %}{% if category %} in <em>{{ category.title }}</em> category{% endif %}:</h3>
  <hr />

  {% include 'django_knowledge/question_list.html' with questions=questions.object_list %}


  {% if not questions.paginator.count %}
    <p class="center"><em>{% trans "No results found." %}</em></p>
  {% endif %}
  
  <hr class="light"/>

  <div class="center">
    <strong>
    {% if questions.has_previous %}
      <a href="?{% page_query request questions.previous_page_number %}">&larr; {% trans "previous" %}</a>
    {% endif %}

    &nbsp; {% blocktrans with number=questions.number pages=questions.paginator.num_pages %}page {{ number }} of {{ page }}{% endblocktrans %} &nbsp;

    {% if questions.has_next %}
      <a href="?{% page_query request questions.next_page_number %}">{% trans "next" %} &rarr;</a>
    {% endif %}
    </strong>
  </div>
</div>

{% if form and paginator.count < 5 %}
  <div class="dk-widget">
    <h3>{% trans "Ask a Question" %}</h3>
    <hr />

    {% url "knowledge_ask" as form_url %}

    {% include "django_knowledge/form.html" with submit_value="Submit this support request" submit_and="and we'll get back to you as soon as possible." submit_url=form_url %}
  </div>
{% endif %}

{% endblock knowledge_widgets %}

knowledge/templates/django_knowledge/mod_bar.html
{% load url from future %}

{% if request.user.is_staff %}
  {% for mod in allowed_mods %}
    <a class="btn{% if mod in node.states %} dk-label-warning{% endif %}" href="{% url "knowledge_moderate" type node.id mod %}">{{ mod }}</a>
  {% endfor %}
{% endif %}

knowledge/templates/django_knowledge/question_list.html
{% load i18n %}
{% load url from future %}

<ol class="question-list">
  {% for question in questions %}
    <li><a href="{{ question.get_absolute_url }}">{{ question.title }}</a>&nbsp; {% if not question.get_responses %}<span class="dk-label dk-label-important">{% trans "no responses" %}</span>{% else %}<span class="dk-label">{{ question.get_responses|length }}&nbsp;responses</span>{% endif %}&nbsp; {% if question.accepted %}<span class="dk-label dk-label-warning">{% trans "accepted" %}</span>&nbsp;{% endif %} {% if question.user.is_staff %}<span class="dk-label dk-label-success">{% trans "staff" %}</span>&nbsp;{% endif %} <small class="quiet">by {{ question.get_name }}</small></li>
  {% endfor %}
</ol>

knowledge/templates/django_knowledge/sidebar.html
{% load i18n %}
{% load url from future %}

{% if my_questions %}

  <h4>{% trans "My Questions" %}</h4>
  <hr />

  <ul>
    {% for question in my_questions %}
      <li><a href="{{ question.get_absolute_url }}">{{ question.title }}</a></li>
    {% empty %}
      <li>You didn't asked anything</li>
    {% endfor %}
  </ul>

  <br />
    
{% endif %}

{% if not hide_category_bar %}
<h4>{% trans "Categories" %}</h4>
<hr />

<ul class="unstyled dk-category-list">
  {% for category in categories %}
    <li><a class="btn" href="{% url "knowledge_list_category" category.slug %}">{{ category.title }}</a></li>
  {% empty %}
    No categories..
  {% endfor %}
</ul>

{% if request.user.is_staff %}
<a class="" href="{% url "category_list" %}">Manage categories</a>
{% endif %}
<br />
{% endif %}

<h4>{% trans "Navigate" %}</h4>
<hr />

<ul>
  <li><a href="{% url "knowledge_ask" %}">{% trans "Ask a question or give suggestion." %}</a></li>
  <li><a href="{% url "knowledge_index" %}">{% trans "Return to homepage." %}</a></li>
</ul>

knowledge/templates/django_knowledge/thread.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}
{% load markup %}
{% load knowledge_tags %}
{% load url from future %}

{% block title %}{{ question.title }}{{ block.super }}{% endblock title %}

{% block knowledge_widgets %}

<div class="dk-widget">

  <div class="dk-dialog alert alert-info">
    <div class="the-author gravatar"><img src="{% get_gravatar question.get_email default='mm' %}" alt="{{ question.get_name }} gravatar"></div>
    <div class="the-content gravatar">
      <h2>{{ question.title }}</h2>
      <h5>{{ question.get_name }} <span class="quiet">
        {% if question.user %}
          {% if question.user.is_staff %}&nbsp;<span class="dk-label dk-label-success">{% trans "staff" %}</span>
          {% else %}&nbsp;<span class="dk-label">{% trans "user" %}</span>{% endif %}
        {% endif %}
        &nbsp;{{ question.added }}
      </span></h5>

      {{ question.body|striptags|markdown:"nl2br" }}

      <div class="dk-mod-bar">
        {% if request.user == question.user or request.user.is_staff %}
          <a class="btn{% if mod in node.states %} dk-label-warning{% endif %}" href="{% url "knowledge_edit" question.id %}">Edit</a>
          {% endif %}

        {% include "django_knowledge/mod_bar.html" with allowed_mods=allowed_mods.question type="question" node=question %}
      </div>

    </div>
  </div> <!-- .dk-dialog -->
    {% if question.categories.all %}
      <span class="dk-thread-categories">Categories:</span>
      {% for category in question.categories.all %}
      <a class="btn" href="{% url "knowledge_list_category" category.slug %}">{{ category.title }}</a></li>
      {% endfor %}
    {% else %}
     <span class="dk-thread-categories">No categories..</span>
    {% endif %}
  </ul>

  <hr />
  <h3>Responses:</h3>
  <hr />

  {% for response in responses %}
    <div class="dk-dialog">
      <div class="the-author gravatar smaller"><img src="{% get_gravatar response.get_email 40 default='mm' %}" alt="{{ response.get_name }} gravatar"></div>
      <div class="the-content gravatar">
        <h5>{{ response.get_name }} <span class="quiet">
          {% if response.accepted %}&nbsp;<span class="dk-label dk-label-warning">{% trans "accepted answer" %}</span>{% endif %}
          {% if question.user == response.user %}&nbsp;<span class="dk-label dk-label-info">{% trans "poster" %}</span>{% endif %}
          {% if response.user %}
            {% if response.user.is_staff %}&nbsp;<span class="dk-label dk-label-success">{% trans "staff" %}</span>
            {% else %}&nbsp;<span class="dk-label">{% trans "user" %}</span>{% endif %}
          {% endif %}
          &nbsp;{{ response.added }}
        </span></h5>

        {{ response.body|striptags|markdown:"nl2br" }}

        <div class="dk-mod-bar">
          {% include "django_knowledge/mod_bar.html" with allowed_mods=allowed_mods.response type="response" node=response %}
        </div>
      </div>
    </div> <!-- .dk-dialog -->
    <hr />
  {% empty %}
    <p class="center"><em>{% trans "No responses yet." %}</em></p>
  {% endfor %}

<!-- 
  <br/> 
  <hr class="light"/>
  <br/> 
 -->

  {% if form %}
    {% include "django_knowledge/form.html" with submit_value="Respond to this question" submit_and="and check back often for updates." %}
  {% else %}
    {% if question.locked %}
      <p class="center"><em>{% trans "This question has been closed." %}</em></p>
    {% else %}
      <p class="center"><em>{% trans "Please log in to respond." %}</em></p>
    {% endif %}
  {% endif %}


</div>

{% endblock knowledge_widgets %}

knowledge/templates/django_knowledge/welcome.html
{% load i18n %}
{% load url from future %}

<div class="dk-roof">
  <h2 class="primary"><a href="{% url "knowledge_index" %}">{% trans "Welcome to our Support Center." %}</a></h2>
  <h4>{% trans "Search for answers to your questions below, or ask your own." %}</h4>
</div>